### ISSUE TITLE
Move work off ODIQueensland

### ISSUE THREAD

**Issue by JDziurlaj** [qcif/data-curator#1006]
If ODIQueensland is defunct, would be it advisable to move work off this account to somewhere else?

**Comment by mattRedBox** [comment]
Hi @JDziurlaj 
It's a good point. I guess at this stage, personally I find that:
- it keeps this project organised with the others (including examples) started with ODI and ODIQueensland. So it kinda makes sense just in terms of where I find this and related work.
- I like the idea of keeping it in a place where @Stephen-Gates is also an overseer, as the project was his concept originally.

But yes perhaps I should fork this project now and place under QCIF, as from a maintenance point of view, it makes more sense there.

I'll leave this open for a bit - there might be other opinions out there. If I keep it here I'll add in other members from QCIF or if I fork the repo, I'll ensure @Stephen-Gates is added back in, and any existing reps from our sponsors.

**Comment by Stephen-Gates** [comment]
I have no problem with forking but a number of other sites point here so a note in the readme point ing to the new location would help. 

Known sites linking here: 
- https://frictionlessdata.io/tooling/labs/
- https://frictionlessdata.io/blog/2019/03/01/datacurator/#using-data-curator
- https://theodi.org/article/odi-toolbox-application-experiments-from-comma-chameleon-to-data-curator/
- http://comma-chameleon.io

**Comment by mattRedBox** [comment]
Thanks @Stephen-Gates Much appreciated. I've also added 2 other devs from QCIF as admins to this repo just as an extra layer of redundancy.

**Comment by mattRedBox** [comment]
Started updating main page (see #1016) and README.md.

**Comment by chris48s** [comment]
It is possible to move a repo without breaking links. If you transfer a repo rather than forking it, github will redirect traffic from the old URL so links won't break. Github will maintain the redirect indefinitely unless you create a new repo with the same name in the old user/org namespace.

There are various example of big projects which moved owner where this redirect still applies e.g:

* https://github.com/kennethreitz/requests --> https://github.com/psf/requests
* https://github.com/robmorgan/phinx --> https://github.com/cakephp/phinx

more info https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by mattRedBox** [comment]
Hi @chris48s
Yep for sure. Sorry for confusion - I think I was considering a fork initially as a conservative way to get started (in case there was resistance to the idea) - I should have made this more clear as discussions with our sponsors have moved on from this. Our sponsors support us moving completely from ODIQueensland to QCIF, knowing that Github will allow the redirects from old site, and I haven't seen any feedback suggest why we shouldn't move.
I've proposed that we do the move as part of our next [Beta release](https://github.com/ODIQueensland/data-curator/milestone/33), and have announced the move in [our news](https://github.com/ODIQueensland/data-curator/issues/15). That way we have a bit of allocated time to fix up any redundant links/refs to ODIQueensland or to the old repo in our integration tests.
So yes a move, not a fork, will be happening within the next couple of weeks - thanks for the pickup :)

**Comment by mattRedBox** [comment]
I'll add this in to our current milestone.
