### ISSUE TITLE
Use latest version of tableschema.js

### ISSUE THREAD

**Issue by Stephen-Gates** [qcif/data-curator#1019]
The [latest version of Tableschema.js](https://github.com/frictionlessdata/tableschema-js/releases) resolved a number of issues, including [validating for leap years](https://github.com/frictionlessdata/tableschema-js/issues/114). It should be used in Data Curator. 

* Data Curator version: 1.2.0 alpha
* Operating System and version: macOS  10.15.4

**Comment by mattRedBox** [comment]
At the moment we're on version 1.9.7 - that was the furthest I could take it to atm, with limited scope I have, without introducing major changes (1.10.0 forwards) into our stack. If I have the time towards the next release I can try to take a look at changes - not sure how much time as there have been several releases, but no changelogs - it may take more time than I have atm to peruse any potentially breaking changes and to code for it.
On the other hand, if the changes aren't too great, and the existing implemented tests hold up, I can look at putting it into the next beta release - I think this is unlikely though for this run.

At the moment, we are looking at implementing parts of #1003 : in particular showing frictionless schema versions used somewhere in the application and/or on export perhaps.
