### ISSUE TITLE
Can no longer export

### ISSUE THREAD

**Issue by JDziurlaj** [qcif/data-curator#1032]
### Current Behaviour (for problems)
When testing `1.2.1-beta`, I can no longer export successfully. I tried a very simple example, and filled in all the usual required information. However, I end up with the *Export package error* of *There is a problem with at least 1 package property. Please check and try again*.

### Steps to Reproduce
- Open -> Comma Seperated
- Fill in Table, Provenance, Package info
- Click Export
### Your Environment

* Data Curator version: 1.2.1-beta
* Operating System and version: Microsoft Windows [Version 10.0.18363.900]

**Comment by mattRedBox** [comment]
Thanks for logging this @JDziurlaj 
I'll have a look at this today.

**Comment by carlhiggs** [comment]
I have installed version 1.2.5.0_x64 from the Microsoft Store, and while some initial trials appeared to work, I just experienced this issue after completing full metadata for my CSV data table with no export being produced.  It generates the "Export package error" of '_There is a problem with at least 1 package property. Please check and try again._', but there is no indication what this error is.  This sounds like it could be the same issue as reported in this closed issue, albeit using the updated release.
![image](https://user-images.githubusercontent.com/12984626/109271445-a4fbe880-7863-11eb-9a1c-2ba98a537e54.png)

Prior to attempting export, I experienced some instability when attempting to add sources (it wouldn't add multiple, with the option to add a source ceasing to work in the Package view; and in the table view, when adding a path for a source it complained of an invalid URL when the URL was valid, and when adding an additional source, the entries for both sources appeared corrupted (all blank except title, which for both replaced with a single character of last key pressed).  I removed all attempts to provide a source, and there were not specific errors marked for this upon attempt to export -- but it didn't work.  So I am not sure if the instability related to sources has resulted in the mysterious error preventing export.

Perhaps this is the same issue, still being an issue?  A possible work around would be if I could export the JSON on its own regardless of errors --- then I wouldn't lose my work, and could perhaps modify this manually.  Currently, I am concerned that if I close the program I will lose the metadata entries already added.  

Here are my windows version details:
![image](https://user-images.githubusercontent.com/12984626/109271347-7d0c8500-7863-11eb-9ab0-256b791ed87c.png)

Cheers, Carl
