### ISSUE TITLE
Where does data package export file go?

### ISSUE THREAD

**Issue by kayakr** [qcif/data-curator#1033]
I imported a TSV, added some column, table and provenance info, validated ok. If I click "Export" icon, I see message "Export package success" and "Data package exported." but there's no indication of the file name or file path, and I can't find any resulting file on my system.

### Desired Behaviour (for feature requests only)
Export of data package or data properties reports success as well as file path and file name saved.

### Current Behaviour (for problems)
Application claims success of export but provides no indication as to where exported file is, or how exported file is named.

### Your Environment
Data Curator 1.2.3-beta on MacOS 10.13.6

**Comment by mattRedBox** [comment]
Hi @kayakr 
It looks like the underlying frictionless library doesn't support anything other than CSV file for export. We had upgraded the library and this wasn't enforced in earlier versions.
The error wasn't being sent up the stack so we can at least make sure this is done so the user has feedback that the export did not succeed.
I'm not sure what to do about Table Schema not allowing non-csv files. I'll have to look at whether we can still ignore this error to allow saving non-csv files, without breaking some other part of the frictionless functionality which we might rely on.
