### ISSUE TITLE
Custom Properties Type checkboxes displaying over option text

### ISSUE THREAD

**Issue by markwheels** [qcif/data-curator#1034]
Selecting 'Settings' to create Custom Properties. Under the 'types' where a selection can be made from the three options  'Column', 'Table' and 'Package', expecting that the checkboxes would be displayed beside or under each of the options.

Instead, I have these three checkboxes displayed with each centered over the top of each of the labels.
![Custom Properties display](https://user-images.githubusercontent.com/48227565/89375357-d7f85680-d730-11ea-8156-6d1db6f035b3.PNG)

* Data Curator 1.2.4-beta
* Windows 10 Pro version1903

**Comment by mattRedBox** [comment]
Thanks for picking this up @markwheels. At the moment I can also see this behaviour in Windows, but haven't seen it yet in my Mac builds. I might try to flick through some of the other panels and see if there's anything else that might be Windows-only GUI problems, before creating fix for this.
