### ISSUE TITLE
Link to help broken

### ISSUE THREAD

**Issue by Stephen-Gates** [qcif/data-curator#1037]
### Expected Behaviour
link to help takes me to help page at https://qcif.github.io/data-curator-help/ 

### Steps to Reproduce

1. Open Data Curator 
2. Select Data Curator Help from the Help menu
3. 404

### Your Environment

* Data Curator version: 1.2.5-beta

**Comment by mattRedBox** [comment]
Appears OK now in released app.

**Comment by Stephen-Gates** [comment]
Correct. Thanks
