### ISSUE TITLE
MacOS binaries can't run

### ISSUE THREAD

**Issue by mccalluc** [qcif/data-curator#1040]
### Current Behaviour (for problems)

Neither of the MacOS binary formats work for me: The zip gives a warning 
> The application "DataCurator" can't be opened.

The DMG gives this error:
> “DataCurator” cannot be opened because the developer cannot be verified.

### Expected Behaviour
Downloads should run.

### Your Environment

* Data Curator version: 1.2.5
* Operating System and version: e.g. macOS Catalina 10.15.5

### Note
May be related to #1005?

**Comment by mattRedBox** [comment]
Hi @mccalluc 
The release for MacOSX is no longer code-signed. You need to follow the usual Mac process for allowing it to open an app from any developer (in System Settings) and then if you Right-click and hold down the "Command" key while selecting 'Open' it will provide you the equivalent option for 'Open anyway'.

**Comment by mattRedBox** [comment]
Hi @mccalluc 
Let me know if you would like me to explain above further, or if that was enough to help open DataCurator.

**Comment by ghost** [comment]
Hi @mccalluc, In case you're unaware of our ["News"](https://github.com/qcif/data-curator/issues/15#issuecomment-846655535), "Data Curator" is now available through the Apple Mac Store - please download from your "App Store" application, rather than through github.
