### ISSUE TITLE
export metadata only (data package schema or table schema)

### ISSUE THREAD

**Issue by pripley123** [qcif/data-curator#986]
### Desired Behaviour

As a data provider
I want the ability to export metadata (data package schema or table schema)
So that I can send my metadata to others to review (without needing to send them my data which may have personal information in it)

**Comment by mattRedBox** [comment]
Hi @pripley123 
I'll raise this with sponsors - it may be unlikely in near future with current timeframes provided for work for this release.
Just to make sure I understand this correctly, does it mean that as a workaround you can export and just send the datapackage.json (I realise it's not as convenient)?

**Comment by pripley123** [comment]
RE: workaround
Yes, that is a workaround; however, as you mentioned not as convenient.

**Comment by mattRedBox** [comment]
Ok thanks @pripley123 understood.

**Comment by mattRedBox** [comment]
Hi @pripley123 
Also short-listing this one as it ties in with considering similar for import enhancements.

**Comment by mattRedBox** [comment]
HI @pripley123 
Export Package Properties as json will be in release-1.2.0-beta, but export table package properties didn't make it into this release due to time spent on #1003 and #988. I'll close this ticket and open up another for Export Table Properties.
