### ISSUE TITLE
Ability to import metadata (data package schema or table schema) without data

### ISSUE THREAD

**Issue by pripley123** [qcif/data-curator#987]
As a data provider and / or a reviewer of metadata
I want the ability to import metadata (data package schema or table schema) without data
so that I can review and (if necessary) modify the metadata without having to have the data (which may have personal information in it)

**Comment by mattRedBox** [comment]
Hi @pripley123 
I'll raise with the sponsors.
See #986 - It's certainly doable - but not sure what we'll have left for time yet after bug-fixes and sponsor priorities.

**Comment by mattRedBox** [comment]
Hi @pripley123 
Sorry i had forgotten about our work in: #852 
It may be that there's less to do here than I first thought. Were you already aware of this work?
![image](https://user-images.githubusercontent.com/5482657/80046125-fbfea600-854c-11ea-9e63-a41f67565b86.png)
Obviously there is your other issue to fix: #972 , but please let me know if this previous work is a step in the right direction

**Comment by mattRedBox** [comment]
Hi @pripley123 
Short-listing this for release.
Let me know if this is still required, but I'm thinking that what I'd look at here is what else could be imported (say at table or package level) besides column properties.

**Comment by pripley123** [comment]
Hi @mattRedBox, thanks for raising with the sponsor and for info the re: importing table schema.   Idea behind this one is a data provider might want to share only the metadata of their data and not the data itself - likely it'd be in the form a data package descriptor.  That data package descriptor would include all the data package and table level attributes (as well as the column attributes).  So if you imagine you received that data package descriptor from a data provider, you'd want to view it (and in some cases suggest changes to the metadata and send it back) so being able to view that metadata in Data Curator would be nice... (https://create.frictionlessdata.io/ allows uploading of data package descriptors but it only shows basic column information).  To be transparent my project is developing a web based tool that will allow for the viewing of data package metadata so probably wouldn't have need of Data Curator for our particular situation, but I think it's still a worthwhile feature.

**Comment by mattRedBox** [comment]
Hi @pripley123 
When opening a data package, without the data, I'm presuming you're OK with the Data Curator opening up a matching number of tabs even if they don't have data? It's difficult for DC to have table descriptors without a matching tab.
I'm not sure what to do yet about data that might already exist - at some point I think we're going to have to look at some sort of Preferences Option to either:
- use existing data
- open in fresh tabs (which is what it does at the moment).
Also the other option to effectively 'reset' Data Curator back to 0 for a data package import (if there is existing data in Data Curator). This would also have to have the same options shown on closing as to prompting the user to save. I'll open these as separate issues.

**Comment by mattRedBox** [comment]
So to follow-up, @pripley123 
- looking at the existing behaviour of [Import Column Properties](#206, #852 ), DC properties would use existing tables I think.
- atm, when Importing Column Properties, the user gets a validation message that the incoming schema doesn't match and won't allow the import, I think if I get the time, I might be able to improve this for both by getting DC to show warning message with OK/cancel prompt. That way it can autofill the missing columns or tables, but a user if free to cancel if there's a particular order that tables or columns need to placed into first.

**Comment by mattRedBox** [comment]
I'll start with Import Package Properties without data as this is the simplest - it will behave the same as Open data package, but with no data.

**Comment by pripley123** [comment]
@mattRedBox re: I'm presuming you're OK with the Data Curator opening up a matching number of tabs even if they don't have data?
Makes sense to me

**Comment by mattRedBox** [comment]
HI @pripley123 
We're releasing an Import Data Package from URL with 1.2.0-beta. Importing from file or importing Table Properties didn't make it into this release due to time spent on #1003 and #988. I'll close this ticket and open up 2 new tickets for this work (Import Table Properties and Import Data Package from file).
